baseURL = "https://www.hzycjy.top"
languageCode = "zh-CN"
title = "Dennis's Blog"
hasCJKLanguage = true
theme = "maupassant-hugo"
enableRobotsTXT = true
PaginatePath = "page"

[author]
    name = "Dennis"
    homepage = "https://www.hzycjy.top"

[params]
    subtitle = "ACM退役老人，C++bug开发者，无情的面试机器"
    keywords = "C++,cpp,go,acm"
    description = "啥也不专注，就想混口饭吃"

    customCSS = ["style.extra.css"]
    customJS = ["app.extra.js"]
    search_provider = "google"

[[params.links]]
  title = "YYcoder的博客"
  name = "YYcoder的博客"
  url = "https://yycoderape.github.io/"

[menu]

  [[menu.main]]
    identifier = "archives"
    name = "归档"
    url = "/archives/"
    weight = 2

  [[menu.main]]
    identifier = "about"
    name = "关于"
    url = "/about/"
    weight = 3

[markup]
    [markup.highlight]
        codeFences = true
        noClasses = true
        tabWidth = 4
        lineNos = true
    [markup.tableOfContents]
        ordered = false
        startLevel = 1